apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "disruptor.fullname" . }}
  labels:
{{ include "disruptor.labels" . | indent 4 }}
rules:
- apiGroups: 
  - ""
  resources: 
  - "configmaps"
  resourceNames: 
  - {{ include "disruptor.fullname" . }}-config 
  verbs: 
  - "get"
- apiGroups: 
  - ""
  resources: 
  - "configmaps"
  resourceNames: 
  - {{ include "disruptor.fullname" . }}-state 
  verbs: 
  - "update"
  - "get"

- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "delete"
  - "create"

- apiGroups:
  - "policy/v1beta1"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "delete"
  - "create"
